package com.chronos.chronos_job_schedular.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;

/*
 * =========================================================
 * AuthResponse (Data Transfer Object)
 * =========================================================
 *
 * ROLE:
 * -----
 * AuthResponse is a DTO used to send authentication results
 * from the backend to the client after a SUCCESSFUL login.
 *
 * Specifically, it carries the JWT token generated by the
 * authentication system.
 *
 * WHY DTO?
 * --------
 * ✔ Prevents exposing internal User entity fields
 * ✔ Sends only required data to the client
 * ✔ Improves API security and clarity
 * ✔ Decouples API contracts from database models
 *
 * WHEN IS IT USED?
 * ----------------
 * ✔ After successful login
 * ✔ Returned by AuthController → /login endpoint
 *
 * SAMPLE JSON RESPONSE:
 * ---------------------
 * {
 *   "token": "eyJhbGciOiJIUzI1NiJ9..."
 * }
 */

@Getter
/*
 * @Getter (Lombok):
 * -----------------
 * Automatically generates a getter method:
 *
 *   public String getToken() { return token; }
 *
 * Benefits:
 * ---------
 * ✔ Reduces boilerplate code
 * ✔ Improves readability
 * ✔ Keeps DTO clean and concise
 */
@AllArgsConstructor
/*
 * @AllArgsConstructor (Lombok):
 * -----------------------------
 * Generates a constructor with all fields:
 *
 *   public AuthResponse(String token) {
 *       this.token = token;
 *   }
 *
 * Usage:
 * ------
 * return new AuthResponse(jwtToken);
 */
public class AuthResponse {

    /*
     * =====================================================
     * JWT TOKEN FIELD
     * =====================================================
     */

    /*
     * JWT Token generated after successful authentication
     *
     * Characteristics:
     * ----------------
     * ✔ Digitally signed
     * ✔ Stateless authentication
     * ✔ Contains user identity (email/role)
     * ✔ Has expiration time
     *
     * CLIENT USAGE:
     * -------------
     * The client must include this token in every secured
     * API request as an HTTP header:
     *
     * Authorization: Bearer <JWT_TOKEN>
     *
     * BACKEND USAGE:
     * --------------
     * - Token is validated in JWT filters
     * - User identity is extracted from token
     * - Access is granted based on roles/permissions
     */
    private String token;
}
