package com.chronos.chronos_job_schedular.repository;

import com.chronos.chronos_job_schedular.entity.JobLog;
import org.springframework.data.jpa.repository.JpaRepository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/*
 * JobLogRepository
 *
 * Purpose:
 * --------
 * This repository interface is used to perform
 * database operations on the JobLog entity.
 *
 * JobLog table stores:
 * - Execution history of jobs
 * - Start & end time of executions
 * - Success / failure status
 * - Log file paths
 *
 * Why use JpaRepository?
 * ----------------------
 * - Provides built-in CRUD operations (save, findById, delete, etc.)
 * - Eliminates boilerplate DAO code
 * - Supports pagination, sorting, and custom queries
 *
 * JpaRepository<JobLog, Long> means:
 * ---------------------------------
 * - JobLog → Entity type
 * - Long   → Primary key type (logId)
 */

public interface JobLogRepository extends JpaRepository<JobLog, Long> {

    /*
     * Find a JobLog by jobId
     *
     * Returns:
     * --------
     * Optional<JobLog>
     *
     * Why Optional?
     * -------------
     * - Prevents NullPointerException
     * - Forces caller to handle "log not found" case
     *
     * Use case:
     * ---------
     * - Used during retry handling
     * - Fetch latest or existing log for a job
     *
     * Query generated by Spring Data:
     * --------------------------------
     * SELECT * FROM job_logs WHERE job_id = ?
     */
    Optional<JobLog> findByJobId(Long jobId);


    /*
     * View all logs for a given job
     *
     * Returns:
     * --------
     * List<JobLog> → All execution attempts of the job
     *
     * Use case:
     * ---------
     * - Job execution history page
     * - Admin monitoring dashboard
     *
     * Query generated:
     * ----------------
     * SELECT * FROM job_logs WHERE job_id = ?
     */
    List<JobLog> findAllByJobId(Long jobId);


    /*
     * View logs by exact start time
     *
     * Parameters:
     * -----------
     * startTime → exact execution start timestamp
     *
     * Use case:
     * ---------
     * - Debugging a specific execution
     * - Searching logs by known execution time
     *
     * Query generated:
     * ----------------
     * SELECT * FROM job_logs WHERE start_time = ?
     */
    List<JobLog> findByStartTime(LocalDateTime startTime);


    /*
     * View logs between a time range
     *
     * Parameters:
     * -----------
     * from → start of time window
     * to   → end of time window
     *
     * Use case:
     * ---------
     * - Fetch logs for a particular day/week
     * - Cleanup old logs
     * - Monitoring recent job executions
     *
     * Query generated:
     * ----------------
     * SELECT * FROM job_logs
     * WHERE start_time BETWEEN ? AND ?
     */
    List<JobLog> findByStartTimeBetween(LocalDateTime from, LocalDateTime to);
}
