package com.chronos.chronos_job_schedular.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/*
 * =========================================================
 * Job Entity
 * =========================================================
 *
 * PURPOSE:
 * --------
 * Represents a schedulable job in the Chronos Job Scheduler system.
 *
 * Each record in this table corresponds to:
 *  ✔ One scheduled job
 *  ✔ One Quartz JobDetail
 *  ✔ One execution configuration
 *
 * RESPONSIBILITIES:
 * -----------------
 * ✔ Store job configuration
 * ✔ Track job execution lifecycle
 * ✔ Support retry mechanism
 * ✔ Enable monitoring and querying
 *
 * DATABASE TABLE:
 * ----------------
 * Table Name → jobs
 *
 * INDEXING STRATEGY:
 * ------------------
 * Indexes are added for:
 * ✔ Faster filtering by status
 * ✔ Faster querying by job type
 * ✔ Efficient scheduler lookups
 * ✔ Monitoring dashboards
 */

@Entity
// Marks this class as a JPA Entity (mapped to a DB table)

@Table(
        name = "jobs",
        /*
         * INDEXES:
         * --------
         * These indexes significantly improve performance
         * for frequently used queries.
         */
        indexes = {
                // Speeds up queries like: find jobs by status
                @Index(name = "idx_job_status", columnList = "status"),

                // Speeds up queries like: find jobs by jobType
                @Index(name = "idx_job_type", columnList = "jobType"),

                // Used by scheduler to fetch upcoming jobs
                @Index(name = "idx_next_execution", columnList = "nextExecutionTime"),

                // Optimizes retry-related queries
                @Index(name = "idx_retry_count", columnList = "retryCount"),

                // Useful for auditing and sorting
                @Index(name = "idx_created_at", columnList = "createdAt"),

                // Composite index for dashboard queries
                @Index(name = "idx_status_type", columnList = "status, jobType")
        }
)
public class Job {

    /* =====================================================
     * 1️⃣ PRIMARY KEY
     * ===================================================== */

    /*
     * jobId:
     * ------
     * ✔ Unique identifier for each job
     * ✔ Auto-generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long jobId;

    /* =====================================================
     * 2️⃣ JOB NAME
     * ===================================================== */

    /*
     * jobName:
     * --------
     * ✔ Human-readable job name
     * ✔ Displayed in dashboards and logs
     */
    @Column(nullable = false)
    private String jobName;

    /* =====================================================
     * 3️⃣ JOB TYPE
     * ===================================================== */

    /*
     * jobType:
     * --------
     * Defines how the job is executed
     *
     * Supported values:
     * ✔ IMMEDIATE  → Runs instantly
     * ✔ ONE_TIME   → Runs once at scheduled time
     * ✔ RECURRING  → Runs repeatedly (cron-based)
     */
    @Column(nullable = false)
    private String jobType;

    /* =====================================================
     * 4️⃣ CREATED AT
     * ===================================================== */

    /*
     * createdAt:
     * ----------
     * ✔ Stores when the job was created
     * ✔ Automatically set at insertion time
     * ✔ Never updated again
     */
    @Column(updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /* =====================================================
     * 5️⃣ START TIME
     * ===================================================== */

    /*
     * startTime:
     * ----------
     * ✔ Time when job should start execution
     * ✔ Used for ONE_TIME and RECURRING jobs
     */
    private LocalDateTime startTime;

    /* =====================================================
     * 6️⃣ TIME DURATION
     * ===================================================== */

    /*
     * timeDuration:
     * -------------
     * ✔ Duration for which job runs (in seconds)
     * ✔ Used by QuartzJobExecutor to simulate execution
     */
    private int timeDuration;

    /* =====================================================
     * 7️⃣ RECURRENCE PATTERN
     * ===================================================== */

    /*
     * recurrencePattern:
     * ------------------
     * Used only for RECURRING jobs
     *
     * Example values:
     * ✔ HOURLY
     * ✔ DAILY
     * ✔ WEEKLY
     * ✔ MONTHLY
     */
    private String recurrencePattern;

    /* =====================================================
     * 8️⃣ NEXT EXECUTION TIME
     * ===================================================== */

    /*
     * nextExecutionTime:
     * ------------------
     * ✔ Stores next trigger time for recurring jobs
     * ✔ Updated after every successful execution
     * ✔ Used for monitoring & dashboards
     */
    private LocalDateTime nextExecutionTime;

    /* =====================================================
     * 9️⃣ JOB STATUS
     * ===================================================== */

    /*
     * status:
     * -------
     * Tracks current job lifecycle state
     *
     * Possible values:
     * ✔ PENDING
     * ✔ RUNNING
     * ✔ SUCCESS
     * ✔ FAILED
     * ✔ CANCELLED
     */
    @Column(nullable = false)
    private String status = "PENDING";

    /* =====================================================
     * 🔟 MAX RETRIES
     * ===================================================== */

    /*
     * maxRetries:
     * -----------
     * ✔ Maximum retry attempts allowed
     * ✔ Used by retry mechanism
     */
    @Column(nullable = false)
    private int maxRetries = 3;

    /* =====================================================
     * 11️⃣ RETRY COUNT
     * ===================================================== */

    /*
     * retryCount:
     * -----------
     * ✔ Tracks number of retries attempted
     * ✔ Incremented on each failure
     */
    @Column(nullable = false)
    private int retryCount = 0;

    /* =====================================================
     * GETTERS & SETTERS
     * =====================================================
     *
     * Used by:
     * ✔ Hibernate
     * ✔ Service layer
     * ✔ Controllers
     */

    public Long getJobId() {
        return jobId;
    }

    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public String getJobType() {
        return jobType;
    }

    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public int getTimeDuration() {
        return timeDuration;
    }

    public void setTimeDuration(int timeDuration) {
        this.timeDuration = timeDuration;
    }

    public String getRecurrencePattern() {
        return recurrencePattern;
    }

    public void setRecurrencePattern(String recurrencePattern) {
        this.recurrencePattern = recurrencePattern;
    }

    public LocalDateTime getNextExecutionTime() {
        return nextExecutionTime;
    }

    public void setNextExecutionTime(LocalDateTime nextExecutionTime) {
        this.nextExecutionTime = nextExecutionTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public int getMaxRetries() {
        return maxRetries;
    }

    public void setMaxRetries(int maxRetries) {
        this.maxRetries = maxRetries;
    }

    public int getRetryCount() {
        return retryCount;
    }

    public void setRetryCount(int retryCount) {
        this.retryCount = retryCount;
    }
}
