package com.chronos.chronos_job_schedular.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/*
 * =========================================================
 * JobLog Entity
 * =========================================================
 *
 * PURPOSE:
 * --------
 * Represents the execution history of jobs in the
 * Chronos Job Scheduler system.
 *
 * Each JobLog record corresponds to:
 * ✔ One execution attempt of a job
 * ✔ One success or failure event
 * ✔ One log file generated by QuartzJobExecutor
 *
 * WHY SEPARATE TABLE?
 * -------------------
 * - A job can run multiple times (especially RECURRING jobs)
 * - Each execution must be stored independently
 * - Helps in auditing, debugging, and monitoring
 *
 * RELATIONSHIP:
 * -------------
 * - Job (Parent)
 * - JobLog (Child)
 * - Relationship is maintained using jobId (logical FK)
 *
 * NOTE:
 * -----
 * We intentionally avoid @ManyToOne mapping to:
 * ✔ Keep logs immutable
 * ✔ Avoid unnecessary joins
 * ✔ Improve write performance
 */

@Entity
// Marks this class as a JPA entity mapped to a database table

@Table(
        name = "job_logs",
        /*
         * INDEXING STRATEGY:
         * ------------------
         * Job logs can grow very large.
         * Indexes are added ONLY on frequently queried fields.
         */
        indexes = {

                /*
                 * idx_job_id:
                 * -----------
                 * ✔ Most common query:
                 *   "Show all logs for a specific job"
                 */
                @Index(name = "idx_job_id", columnList = "jobId"),

                /*
                 * idx_job_status:
                 * ----------------
                 * ✔ Used to filter logs by result
                 * ✔ Example: FAILED jobs for alerting
                 */
                @Index(name = "idx_job_status", columnList = "jobStatus"),

                /*
                 * idx_job_id_status:
                 * ------------------
                 * ✔ Optimizes combined queries like:
                 *   "Show FAILED logs of jobId = X"
                 */
                @Index(name = "idx_job_id_status", columnList = "jobId, jobStatus"),

                /*
                 * idx_start_time:
                 * ----------------
                 * ✔ Used for:
                 *   - Recent execution history
                 *   - Cleanup jobs
                 *   - Time-based analytics
                 */
                @Index(name = "idx_start_time", columnList = "startTime")
        }
)
public class JobLog {

    /* =====================================================
     * 1️⃣ PRIMARY KEY
     * ===================================================== */

    /*
     * logId:
     * ------
     * ✔ Unique identifier for each execution log
     * ✔ Auto-generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long logId;

    /* =====================================================
     * 2️⃣ JOB IDENTIFICATION
     * ===================================================== */

    /*
     * jobId:
     * ------
     * ✔ References the Job that was executed
     * ✔ Stored as a simple column for performance
     * ✔ Indexed for fast lookup
     */
    @Column(nullable = false)
    private Long jobId;

    /*
     * jobName:
     * --------
     * ✔ Stored redundantly for readability
     * ✔ Allows viewing logs without joining Job table
     */
    private String jobName;

    /*
     * jobType:
     * --------
     * ✔ IMMEDIATE / ONE_TIME / RECURRING
     * ✔ Helps filter execution history
     *
     * NOTE:
     * -----
     * No index added because this field
     * is not frequently filtered alone
     */
    private String jobType;

    /* =====================================================
     * 3️⃣ EXECUTION TIMESTAMPS
     * ===================================================== */

    /*
     * startTime:
     * ----------
     * ✔ When the job execution started
     * ✔ Used for timeline tracking
     * ✔ Indexed for recent-history queries
     */
    private LocalDateTime startTime;

    /*
     * endTime:
     * --------
     * ✔ When execution finished
     * ✔ Used to calculate execution duration
     */
    private LocalDateTime endTime;

    /*
     * nextExecutionTime:
     * ------------------
     * ✔ Applicable ONLY for RECURRING jobs
     * ✔ Stores next trigger time after execution
     * ✔ NULL for IMMEDIATE / ONE_TIME jobs
     */
    private LocalDateTime nextExecutionTime;

    /* =====================================================
     * 4️⃣ EXECUTION STATUS & LOG FILE
     * ===================================================== */

    /*
     * jobStatus:
     * ----------
     * Indicates result of execution
     *
     * Possible values:
     * ✔ SUCCESS
     * ✔ FAILED
     */
    @Column(nullable = false)
    private String jobStatus;

    /*
     * logFilePath:
     * ------------
     * ✔ Absolute path of the log file
     * ✔ Generated by QuartzJobExecutor
     * ✔ Used for debugging and audits
     */
    private String logFilePath;

    /* =====================================================
     * GETTERS & SETTERS
     * =====================================================
     *
     * Used by:
     * ✔ Hibernate
     * ✔ Service layer
     * ✔ Controllers
     */

    public Long getLogId() {
        return logId;
    }

    public void setLogId(Long logId) {
        this.logId = logId;
    }

    public Long getJobId() {
        return jobId;
    }

    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public String getJobType() {
        return jobType;
    }

    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public LocalDateTime getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    public LocalDateTime getNextExecutionTime() {
        return nextExecutionTime;
    }

    public void setNextExecutionTime(LocalDateTime nextExecutionTime) {
        this.nextExecutionTime = nextExecutionTime;
    }

    public String getJobStatus() {
        return jobStatus;
    }

    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus;
    }

    public String getLogFilePath() {
        return logFilePath;
    }

    public void setLogFilePath(String logFilePath) {
        this.logFilePath = logFilePath;
    }
}
